### ISSUE TITLE
Error in onChange callback:  TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by keremcankabadayi** [mariohmol/ang-jsoneditor#64]
**Describe the bug**
`this.editor` throws me error whatever i try.

**To Reproduce**
Here my codes:

`<json-editor #editor formControlName="body" *ngIf="this.mockForm.get('userResponseSelection').value == '1'" class="col-md-12" [options]="options" [data]="data" (jsonChange)="changeLog($event)"></json-editor>`

```
 @ViewChild('editor', {static: true}) editor: JsonEditorComponent;

  options = new JsonEditorOptions();

  data = {
    products: [{
      name: 'car',
      product: [{
        name: 'honda',
        model: [
          {id: 'civic', name: 'civic'},
          {id: 'accord', name: 'accord'},
          {id: 'crv', name: 'crv'},
          {id: 'pilot', name: 'pilot'},
          {id: 'odyssey', name: 'odyssey'}
        ]
      }]
    }]
  };

  constructor(private formBuilder: FormBuilder, private alertifyService: AlertifyService, private mockService: MockService, private formFillingService: FormFillingService) {
    this.options.mode = 'code';
    this.options.modes = ['code', 'text', 'tree', 'view'];
    this.options.onChange = () => {
      console.log(this.editor.get());
    }
    this.editor = new JsonEditorComponent;
  }
```

my console while typing every single char

![image](https://user-images.githubusercontent.com/23381187/80542961-a72cb680-89b6-11ea-9d6c-8b3a5e55655a.png)

**Expected behavior**
To get this.editor object onChange

**Desktop (please complete the following information):**
 ```
   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.26
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cdk                      8.2.3
@angular/cli                      8.3.26
@angular/material                 8.2.3
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

```

**Additional context**
I tried to run a small demo like here https://stackblitz.com/edit/angular-gx54gz?file=src%2Fapp%2Fapp.component.html, it did work but it couldnt work out at my real case.

**Comment by mariohmol** [comment]
Hi could u find out?

Try to follow the demo that way:

https://github.com/mariohmol/ang-jsoneditor/blob/master/src/app/demo/demo.component.html#L28

**Comment by LaXiS96** [comment]
Hello,
I have been banging my head against this same problem for the past 3 hours and the solution is pretty logical in the end...

In your ViewChild declaration, you have told Angular that the component is static (`{ static: true }`): this is only useful when the component you are referencing is never destroyed and recreated dynamically, because the child query is evaluated only once at the Init of the parent component.
In your template, you have a `*ngIf` directive on `<json-editor ...>` (the same would be applicable if the `*ngIf` were on a parent container): this means that Angular is going to evaluate the directive at every change detection cycle, destroying and recreating the component depending on the result of the directive expression.
This is why your `this.editor` is always `undefined`, because the ViewChild query is run when the JsonEditorComponent doesn't exist yet and then never again.

The quick solution is therefore removing `{ static: true }` or setting it to `false`, so that the ViewChild query runs on every change detection cycle.

**Comment by mariohmol** [comment]
Owww!! Good catch!!

But where we have the *ngIf ? I didnt see it here

**Comment by LaXiS96** [comment]
The issue is not present/noticeable in the demo, as both `#editor` and `#editorTwo` are effectively static (specified in the HTML template with no Angular directives on them or their parents).

In @keremcankabadayi 's case, `*ngIf` is the third attribute on `<json-editor ...>`

**Comment by mariohmol** [comment]
I see... 

is any side effects of changing that to false?

what happens if you put he *ngIf in a parent container?

**Comment by LaXiS96** [comment]
No side effect that I'm aware of, also considering that `static: false` is the default anyway since Angular 9.
For a better explanation of the `static` property see [this](https://stackoverflow.com/questions/56359504/how-should-i-use-the-new-static-option-for-viewchild-in-angular-8) StackOverflow question.

Putting the `*ngIf` on a parent container does not change this behavior, because Angular removes the full content of the container from the DOM if the expression evaluates to false, and recreates everything when it evaluates to true.

**Comment by mariohmol** [comment]
i see.. i thought that static true was the default (to be honest my apps stills in v8)

thanks for this.. submitted a new version with this change...

if the problem persists pls reopen!

**Comment by mariohmol** [comment]
that broke that build =(

**Comment by mariohmol** [comment]
No it cant find the nativeelement on ngOnInit.. 

```ts
if (!this.jsonEditorContainer.nativeElement) {
      console.error(`Can't find the ElementRef reference for jsoneditor)`);
    }
```

**Comment by LaXiS96** [comment]
That is as expected: with `static: true` the `ViewChild` query is resolved at `ngOnInit`, with `static: false` it's resolved at `ngAfterViewInit`. See the migration guide i linked earlier.

There is no need to change it in [jsoneditor.component.ts](https://github.com/mariohmol/ang-jsoneditor/blob/master/ang-jsoneditor/src/jsoneditor/jsoneditor.component.ts#L32) because your template `<div [id]="id" #jsonEditorContainer></div>` does not use any directive that could cause the `div` to be dynamically recreated, so it is safe to consider it static and have it available at `ngOnInit`.

**Comment by mariohmol** [comment]
but what about when this is rerenderer?

**Comment by mariohmol** [comment]
wait... so Its not needed to change in this component? just in the example?

**Comment by LaXiS96** [comment]
Yes, only in the example, so that people directly copying the example won't end up in this situation.

This situation does not apply for `JsonEditorComponent` because the `div` is effectively static.

Always remember that your component's template has the same lifetime as the component itself: this means that if Angular decides that your component must be destroyed (ideally because some parent container has some directive like `*ngIf`), it will also remove its elements from the DOM. When Angular recreates your component, it will also recreate the template in the DOM. This means that, from the component's perspective, the element is indeed static, because it always exists when the component itself exists.

**Comment by mariohmol** [comment]
True!

Did the demo with a button to toggle... thanks
